import torch
import pickle
import pandas as pd
from typing import Dict
from torch.utils.data import Dataset
from torch_geometric.data import Batch

class PreprocessedGraphDataset(Dataset):
    def __init__(self, graph_path: str, emb_dict: Dict[str, torch.Tensor] = None):
        """
        Args:
            graph_path: path to the .pkl file (generated by preprocessing.py)
            emb_dict: Dictionnary {id: embedding} for the training
        """
        print(f"Loading pre-computed graphs from: {graph_path}")
        with open(graph_path, 'rb') as f:
            self.graphs = pickle.load(f)
            
        self.emb_dict = emb_dict
        print(f"Loaded {len(self.graphs)} graphs ready for training.")

    def __len__(self):
        return len(self.graphs)

    def __getitem__(self, idx):
        graph = self.graphs[idx]
        
        if self.emb_dict is not None:
            g_id = str(graph.id) 
            text_emb = self.emb_dict[g_id]
            
            # Everything we will need later
            return graph, graph.sorted_neighbors, graph.geo_features, text_emb
        else:
            return graph, graph.sorted_neighbors, graph.geo_features